services:
  mysql:
    platform: linux/amd64
    image: mysql:8.0
    container_name: mysql
    ports:
      - "13306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: maze 
      MYSQL_DEFAULT_AUTHENTICATION_PLUGIN: mysql_native_password
    volumes:
      - mysql_data:/var/lib/mysql
      - ./db/initdb:/docker-entrypoint-initdb.d
    networks:
      - pc2-network

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: phpmyadmin
    restart: always
    ports:
      - "8080:80"
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: root
    networks:
      - pc2-network
    depends_on:
      - mysql

  movements:
    build: .
    command: python ./scripts/moves_to_sql.py
    depends_on:
      - mysql
    networks:
      - pc2-network

  temperature:
    build: .
    command: python ./scripts/temps_to_sql.py
    depends_on:
      - mysql
    networks:
      - pc2-network
    environment:
      - PYTHONUNBUFFERED=0


  sound:
    build: .
    command: python ./scripts/sounds_to_sql.py
    depends_on:
      - mysql
    networks:
      - pc2-network

volumes:
  mysql_data:

networks:
  pc2-network:
