services:
  mysql:
    platform: linux/amd64
    image: mysql:8.0
    container_name: mysql
    ports:
      - "13306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: maze
      MYSQL_DEFAULT_AUTHENTICATION_PLUGIN: mysql_native_password
    volumes:
      - mysql_data:/var/lib/mysql
      - ./db/initdb:/docker-entrypoint-initdb.d
    networks:
      - pc2-network

  web:
    image: php:apache
    container_name: web
    volumes:
      - ./scripts/php:/var/www/html
    ports:
      - "8080:80"
    depends_on:
      - mysql

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: phpmyadmin
    restart: always
    ports:
      - "8081:80"
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: root
    networks:
      - pc2-network
    depends_on:
      - mysql

  movements:
    build:
      context: ..
      dockerfile: PC2/Dockerfile
    container_name: movements
    command: python ./PC2/receiver/receiver_movimentos.py
    depends_on:
      - mysql
    networks:
      - pc2-network
    environment:
      - PYTHONUNBUFFERED=1

  temperature:
    build:
      context: ..
      dockerfile: PC2/Dockerfile
    container_name: temperature
    command: python ./PC2/receiver/receiver_temperatura.py
    depends_on:
      - mysql
    networks:
      - pc2-network
    environment:
      - PYTHONUNBUFFERED=1

  sound:
    build:
      context: ..
      dockerfile: PC2/Dockerfile
    container_name: sound
    command: python ./PC2/receiver/receiver_ruido.py
    depends_on:
      - mysql
    networks:
      - pc2-network
    environment:
      - PYTHONUNBUFFERED=1

volumes:
  mysql_data:

networks:
  pc2-network:
